service:
  type: LoadBalancer
persistence:
  enabled: true
persistence:
  size: 1Gi
persistence:
  storageClassName: retain
resources:
  requests:
      memory: 100Mi
      cpu: 100m
  limits:
      memory: 300Mi
      cpu: 200m
plugins:
  - grafana-image-renderer
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true
dashboards:
  Erlang-Distribution:
      gnetId: 11352
      revision: 5
      datasource: Prometheus