server:
  resources:
    requests:
        memory: 100Mi
        cpu: 100m
    limits:
        memory: 800Mi
        cpu: 500m

global:
  scrape_interval: 10s

serverFiles:
  prometheus.yml:
    scrape_configs:
    
    - job_name: 'policyengine'
      scrape_interval: 5s
      static_configs:
      - targets: ['rabbitmq.test-rabbitmq.svc.cluster.local:15692']
        labels:
          group: 'services'