kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  type: LoadBalancer
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: prom
     protocol: TCP
     port: 15692
     targetPort: 15692
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
   - name: amqpssl
     protocol: TCP
     port: 5671
     targetPort: 5671
  selector:
    app: rabbitmq